### ISSUE TITLE
Iterate through all types and subtypes specified in the HTTP 'Accept' header

### ISSUE THREAD

**Issue by CheungJ** [sideshowcoder/canned#100]
The HTTP `Accept` header is a mechanism for the client to tell the server which [media types are acceptable for the response](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html).

Canned only checks the first subtype in the `Accept` header, but if a file does not exist with the first subtype, it does not attempt to check for a file matching the following subtypes.

**Comment by sideshowcoder** [comment]
This is true and so far has been by design, the reason being that as canned from my side has been used for testing I wanted the matching to be rather strict, as `Accept` headers are something notoriously handled in odd ways except the bare minimum. I can see the reason so why one would like it to be less strict, if possible even resemble different kind of backends (aka Rails does different things than Spring etc.)
I'm happy to accept PRs changing this behaviour but would encourage it to be behind a command line option if at all possible.

**Comment by CheungJ** [comment]
I've created a PR for a "dumb" version of this issue: https://github.com/sideshowcoder/canned/pull/103

**Comment by sideshowcoder** [comment]
Awesome thanks for your work, I'm currently at a conference so I can't review but I will as soon as I'm back on Thursday. Thanks again cheers!

**Comment by CheungJ** [comment]
Cool, thanks! Enjoy the conference! :)

**Comment by sideshowcoder** [comment]
Thanks this is now available in 0.3.9! Great work!

**Comment by CheungJ** [comment]
Great! Thanks! I plan to contribute more in future.

**Comment by sideshowcoder** [comment]
Happy to hear! feel free to contact me on twitter https://twitter.com/ischi for quick things or we can jump into the gitter chat if need be 👍
